### ISSUE TITLE
Building `jax > v0.4.35` on MacOS (arm64) gives `error: defining a type within 'offsetof' is a Clang extension`

### ISSUE THREAD

**Issue by tttc3** [jax-ml/jax#25530]
### Description

Using the new build api, introduced in 676151265859f8b0dd8baf6f6ae50c3367ed0509 (released in `jax-v0.4.36`), 
```bash
python build/build.py build --wheels=jaxlib --verbose   
```
I get the following error
```bash
external/upb/upb/upb.c:192:10: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  192 |   n &= ~(upb_alignof(upb_arena) - 1);
      |          ^~~~~~~~~~~~~~~~~~~~~~
external/upb/upb/upb.c:183:37: note: expanded from macro 'upb_alignof'
  183 | #define upb_alignof(type) offsetof (struct { char c; type member; }, member)
      |                                     ^~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
1 error generated.
Error in child process '/usr/bin/xcrun'. 1
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 240.713s, Critical Path: 122.31s
INFO: 2834 processes: 26 internal, 2808 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
2024-12-17 15:09:44,790 - DEBUG - Command finished with return code 1
```

The issue appears to be resolved by modifying the following lines in `build/build.py`
```python
# Do not apply --config=clang on Mac as these settings do not apply to
# Apple Clang.
# if os_name != "darwin":   # Disabling the conditional fixes the error.
wheel_build_command.append("--config=clang")
```
However, due to the preceding code comment, I'm not sure if this is a valid modification?

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.38.dev20241217+0ec902df8
jaxlib: 0.4.38.dev20241217
numpy:  2.2.0
python: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ]
device info: cpu-1, 1 local devices"
process_count: 1
platform: uname_result(system='Darwin', node='main', release='24.1.0', version='Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:23 PDT 2024', machine='arm64')
```

**Comment by nitins17** [comment]
Thanks! I sent https://github.com/jax-ml/jax/pull/25543 to fix. It looks like we only need it on newer Clang versions.
